spring:
  profiles:
    active: debug #在这里指定使用哪个配置文件
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_springboot
      username: root
      password: root
  jpa:
    hibernate:
      #ddl-auto: create #自动建表,每次都会创建空表
      #ddl-auto: create-drop #自动建表,应用停止时将表删除
      #ddl-auto: validate #验证表结构是否一致，不一致报错
      #ddl-auto: none #什么也不做
      ddl-auto: update #自动建表
    show-sql: true

  redis:
    host: # Redis服务器地址
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
    password: # Redis服务器连接密码（默认为空）
    port: 6379
    database: 0 #Redis数据库索引（默认为0）

  http:
   multipart:
     enabled: true #默认支持文件上传.
     file-size-threshold: 0 #支持文件写入磁盘.
    # location: ./upload/tmp/ # 上传文件的临时目录
     max-file-size: 5MB # 最大支持文件大小
     max-request-size: 10MB # 最大支持请求大小

  #mvc:
    #view:
      #suffix: .html

#日志
logurl: ./log/springbootdemo.log
logging:
  #指定日志存放文件
  file: ${logurl}
  level: debug



#自定义属性,需要有对应的类，然后通过Autowired即可使用
#优先级较低，如果active中的配置文件也有相同的属性则以其为准，下面的属性就失效了
Girl:
  name: junmeng
  age: 18

custom: Thymeleaf
